// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/log.proto

package in.xnnyygn.xraft.core.log;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NodeConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <code>string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 3;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code NodeConfig}
   */
  public  static final class NodeConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NodeConfig)
      NodeConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeConfig.newBuilder() to construct.
    private NodeConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeConfig() {
      id_ = "";
      host_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.xnnyygn.xraft.core.log.Protos.NodeConfig.class, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.xnnyygn.xraft.core.log.Protos.NodeConfig)) {
        return super.equals(obj);
      }
      in.xnnyygn.xraft.core.log.Protos.NodeConfig other = (in.xnnyygn.xraft.core.log.Protos.NodeConfig) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.xnnyygn.xraft.core.log.Protos.NodeConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NodeConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NodeConfig)
        in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.xnnyygn.xraft.core.log.Protos.NodeConfig.class, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder.class);
      }

      // Construct using in.xnnyygn.xraft.core.log.Protos.NodeConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        host_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeConfig_descriptor;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig getDefaultInstanceForType() {
        return in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance();
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig build() {
        in.xnnyygn.xraft.core.log.Protos.NodeConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig buildPartial() {
        in.xnnyygn.xraft.core.log.Protos.NodeConfig result = new in.xnnyygn.xraft.core.log.Protos.NodeConfig(this);
        result.id_ = id_;
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.xnnyygn.xraft.core.log.Protos.NodeConfig) {
          return mergeFrom((in.xnnyygn.xraft.core.log.Protos.NodeConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.xnnyygn.xraft.core.log.Protos.NodeConfig other) {
        if (other == in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.xnnyygn.xraft.core.log.Protos.NodeConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.xnnyygn.xraft.core.log.Protos.NodeConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 2;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NodeConfig)
    }

    // @@protoc_insertion_point(class_scope:NodeConfig)
    private static final in.xnnyygn.xraft.core.log.Protos.NodeConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.xnnyygn.xraft.core.log.Protos.NodeConfig();
    }

    public static in.xnnyygn.xraft.core.log.Protos.NodeConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeConfig>
        PARSER = new com.google.protobuf.AbstractParser<NodeConfig>() {
      @java.lang.Override
      public NodeConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public in.xnnyygn.xraft.core.log.Protos.NodeConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddNodeCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddNodeCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> 
        getNodeConfigsList();
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeConfig getNodeConfigs(int index);
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    int getNodeConfigsCount();
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
        getNodeConfigsOrBuilderList();
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNodeConfigsOrBuilder(
        int index);

    /**
     * <code>.NodeConfig new_node_config = 2;</code>
     */
    boolean hasNewNodeConfig();
    /**
     * <code>.NodeConfig new_node_config = 2;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeConfig getNewNodeConfig();
    /**
     * <code>.NodeConfig new_node_config = 2;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNewNodeConfigOrBuilder();
  }
  /**
   * Protobuf type {@code AddNodeCommand}
   */
  public  static final class AddNodeCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddNodeCommand)
      AddNodeCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddNodeCommand.newBuilder() to construct.
    private AddNodeCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddNodeCommand() {
      nodeConfigs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddNodeCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nodeConfigs_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeConfig>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeConfigs_.add(
                  input.readMessage(in.xnnyygn.xraft.core.log.Protos.NodeConfig.parser(), extensionRegistry));
              break;
            }
            case 18: {
              in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder subBuilder = null;
              if (newNodeConfig_ != null) {
                subBuilder = newNodeConfig_.toBuilder();
              }
              newNodeConfig_ = input.readMessage(in.xnnyygn.xraft.core.log.Protos.NodeConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(newNodeConfig_);
                newNodeConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nodeConfigs_ = java.util.Collections.unmodifiableList(nodeConfigs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.Builder.class);
    }

    private int bitField0_;
    public static final int NODE_CONFIGS_FIELD_NUMBER = 1;
    private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> nodeConfigs_;
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> getNodeConfigsList() {
      return nodeConfigs_;
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
        getNodeConfigsOrBuilderList() {
      return nodeConfigs_;
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public int getNodeConfigsCount() {
      return nodeConfigs_.size();
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeConfig getNodeConfigs(int index) {
      return nodeConfigs_.get(index);
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNodeConfigsOrBuilder(
        int index) {
      return nodeConfigs_.get(index);
    }

    public static final int NEW_NODE_CONFIG_FIELD_NUMBER = 2;
    private in.xnnyygn.xraft.core.log.Protos.NodeConfig newNodeConfig_;
    /**
     * <code>.NodeConfig new_node_config = 2;</code>
     */
    public boolean hasNewNodeConfig() {
      return newNodeConfig_ != null;
    }
    /**
     * <code>.NodeConfig new_node_config = 2;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeConfig getNewNodeConfig() {
      return newNodeConfig_ == null ? in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance() : newNodeConfig_;
    }
    /**
     * <code>.NodeConfig new_node_config = 2;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNewNodeConfigOrBuilder() {
      return getNewNodeConfig();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodeConfigs_.size(); i++) {
        output.writeMessage(1, nodeConfigs_.get(i));
      }
      if (newNodeConfig_ != null) {
        output.writeMessage(2, getNewNodeConfig());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodeConfigs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodeConfigs_.get(i));
      }
      if (newNodeConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNewNodeConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.xnnyygn.xraft.core.log.Protos.AddNodeCommand)) {
        return super.equals(obj);
      }
      in.xnnyygn.xraft.core.log.Protos.AddNodeCommand other = (in.xnnyygn.xraft.core.log.Protos.AddNodeCommand) obj;

      boolean result = true;
      result = result && getNodeConfigsList()
          .equals(other.getNodeConfigsList());
      result = result && (hasNewNodeConfig() == other.hasNewNodeConfig());
      if (hasNewNodeConfig()) {
        result = result && getNewNodeConfig()
            .equals(other.getNewNodeConfig());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeConfigsCount() > 0) {
        hash = (37 * hash) + NODE_CONFIGS_FIELD_NUMBER;
        hash = (53 * hash) + getNodeConfigsList().hashCode();
      }
      if (hasNewNodeConfig()) {
        hash = (37 * hash) + NEW_NODE_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getNewNodeConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.xnnyygn.xraft.core.log.Protos.AddNodeCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddNodeCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddNodeCommand)
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.Builder.class);
      }

      // Construct using in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeConfigsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodeConfigsBuilder_ == null) {
          nodeConfigs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodeConfigsBuilder_.clear();
        }
        if (newNodeConfigBuilder_ == null) {
          newNodeConfig_ = null;
        } else {
          newNodeConfig_ = null;
          newNodeConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_descriptor;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand getDefaultInstanceForType() {
        return in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.getDefaultInstance();
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand build() {
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand buildPartial() {
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommand result = new in.xnnyygn.xraft.core.log.Protos.AddNodeCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (nodeConfigsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodeConfigs_ = java.util.Collections.unmodifiableList(nodeConfigs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodeConfigs_ = nodeConfigs_;
        } else {
          result.nodeConfigs_ = nodeConfigsBuilder_.build();
        }
        if (newNodeConfigBuilder_ == null) {
          result.newNodeConfig_ = newNodeConfig_;
        } else {
          result.newNodeConfig_ = newNodeConfigBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.xnnyygn.xraft.core.log.Protos.AddNodeCommand) {
          return mergeFrom((in.xnnyygn.xraft.core.log.Protos.AddNodeCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.xnnyygn.xraft.core.log.Protos.AddNodeCommand other) {
        if (other == in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.getDefaultInstance()) return this;
        if (nodeConfigsBuilder_ == null) {
          if (!other.nodeConfigs_.isEmpty()) {
            if (nodeConfigs_.isEmpty()) {
              nodeConfigs_ = other.nodeConfigs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeConfigsIsMutable();
              nodeConfigs_.addAll(other.nodeConfigs_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeConfigs_.isEmpty()) {
            if (nodeConfigsBuilder_.isEmpty()) {
              nodeConfigsBuilder_.dispose();
              nodeConfigsBuilder_ = null;
              nodeConfigs_ = other.nodeConfigs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodeConfigsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeConfigsFieldBuilder() : null;
            } else {
              nodeConfigsBuilder_.addAllMessages(other.nodeConfigs_);
            }
          }
        }
        if (other.hasNewNodeConfig()) {
          mergeNewNodeConfig(other.getNewNodeConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.xnnyygn.xraft.core.log.Protos.AddNodeCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> nodeConfigs_ =
        java.util.Collections.emptyList();
      private void ensureNodeConfigsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodeConfigs_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeConfig>(nodeConfigs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> nodeConfigsBuilder_;

      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> getNodeConfigsList() {
        if (nodeConfigsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeConfigs_);
        } else {
          return nodeConfigsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public int getNodeConfigsCount() {
        if (nodeConfigsBuilder_ == null) {
          return nodeConfigs_.size();
        } else {
          return nodeConfigsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig getNodeConfigs(int index) {
        if (nodeConfigsBuilder_ == null) {
          return nodeConfigs_.get(index);
        } else {
          return nodeConfigsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder setNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (nodeConfigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeConfigsIsMutable();
          nodeConfigs_.set(index, value);
          onChanged();
        } else {
          nodeConfigsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder setNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder builderForValue) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeConfigsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (nodeConfigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(value);
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (nodeConfigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(index, value);
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(
          in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder builderForValue) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(builderForValue.build());
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder builderForValue) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addAllNodeConfigs(
          java.lang.Iterable<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfig> values) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeConfigs_);
          onChanged();
        } else {
          nodeConfigsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder clearNodeConfigs() {
        if (nodeConfigsBuilder_ == null) {
          nodeConfigs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodeConfigsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder removeNodeConfigs(int index) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.remove(index);
          onChanged();
        } else {
          nodeConfigsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder getNodeConfigsBuilder(
          int index) {
        return getNodeConfigsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNodeConfigsOrBuilder(
          int index) {
        if (nodeConfigsBuilder_ == null) {
          return nodeConfigs_.get(index);  } else {
          return nodeConfigsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
           getNodeConfigsOrBuilderList() {
        if (nodeConfigsBuilder_ != null) {
          return nodeConfigsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeConfigs_);
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder addNodeConfigsBuilder() {
        return getNodeConfigsFieldBuilder().addBuilder(
            in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder addNodeConfigsBuilder(
          int index) {
        return getNodeConfigsFieldBuilder().addBuilder(
            index, in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder> 
           getNodeConfigsBuilderList() {
        return getNodeConfigsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
          getNodeConfigsFieldBuilder() {
        if (nodeConfigsBuilder_ == null) {
          nodeConfigsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder>(
                  nodeConfigs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodeConfigs_ = null;
        }
        return nodeConfigsBuilder_;
      }

      private in.xnnyygn.xraft.core.log.Protos.NodeConfig newNodeConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> newNodeConfigBuilder_;
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public boolean hasNewNodeConfig() {
        return newNodeConfigBuilder_ != null || newNodeConfig_ != null;
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig getNewNodeConfig() {
        if (newNodeConfigBuilder_ == null) {
          return newNodeConfig_ == null ? in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance() : newNodeConfig_;
        } else {
          return newNodeConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public Builder setNewNodeConfig(in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (newNodeConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          newNodeConfig_ = value;
          onChanged();
        } else {
          newNodeConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public Builder setNewNodeConfig(
          in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder builderForValue) {
        if (newNodeConfigBuilder_ == null) {
          newNodeConfig_ = builderForValue.build();
          onChanged();
        } else {
          newNodeConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public Builder mergeNewNodeConfig(in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (newNodeConfigBuilder_ == null) {
          if (newNodeConfig_ != null) {
            newNodeConfig_ =
              in.xnnyygn.xraft.core.log.Protos.NodeConfig.newBuilder(newNodeConfig_).mergeFrom(value).buildPartial();
          } else {
            newNodeConfig_ = value;
          }
          onChanged();
        } else {
          newNodeConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public Builder clearNewNodeConfig() {
        if (newNodeConfigBuilder_ == null) {
          newNodeConfig_ = null;
          onChanged();
        } else {
          newNodeConfig_ = null;
          newNodeConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder getNewNodeConfigBuilder() {
        
        onChanged();
        return getNewNodeConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNewNodeConfigOrBuilder() {
        if (newNodeConfigBuilder_ != null) {
          return newNodeConfigBuilder_.getMessageOrBuilder();
        } else {
          return newNodeConfig_ == null ?
              in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance() : newNodeConfig_;
        }
      }
      /**
       * <code>.NodeConfig new_node_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
          getNewNodeConfigFieldBuilder() {
        if (newNodeConfigBuilder_ == null) {
          newNodeConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder>(
                  getNewNodeConfig(),
                  getParentForChildren(),
                  isClean());
          newNodeConfig_ = null;
        }
        return newNodeConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddNodeCommand)
    }

    // @@protoc_insertion_point(class_scope:AddNodeCommand)
    private static final in.xnnyygn.xraft.core.log.Protos.AddNodeCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.xnnyygn.xraft.core.log.Protos.AddNodeCommand();
    }

    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddNodeCommand>
        PARSER = new com.google.protobuf.AbstractParser<AddNodeCommand>() {
      @java.lang.Override
      public AddNodeCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddNodeCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddNodeCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddNodeCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RemoveNodeCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RemoveNodeCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> 
        getNodeConfigsList();
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeConfig getNodeConfigs(int index);
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    int getNodeConfigsCount();
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
        getNodeConfigsOrBuilderList();
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNodeConfigsOrBuilder(
        int index);

    /**
     * <code>string node_to_remove = 2;</code>
     */
    java.lang.String getNodeToRemove();
    /**
     * <code>string node_to_remove = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeToRemoveBytes();
  }
  /**
   * Protobuf type {@code RemoveNodeCommand}
   */
  public  static final class RemoveNodeCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RemoveNodeCommand)
      RemoveNodeCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RemoveNodeCommand.newBuilder() to construct.
    private RemoveNodeCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RemoveNodeCommand() {
      nodeConfigs_ = java.util.Collections.emptyList();
      nodeToRemove_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RemoveNodeCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nodeConfigs_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeConfig>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeConfigs_.add(
                  input.readMessage(in.xnnyygn.xraft.core.log.Protos.NodeConfig.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeToRemove_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nodeConfigs_ = java.util.Collections.unmodifiableList(nodeConfigs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.Builder.class);
    }

    private int bitField0_;
    public static final int NODE_CONFIGS_FIELD_NUMBER = 1;
    private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> nodeConfigs_;
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> getNodeConfigsList() {
      return nodeConfigs_;
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
        getNodeConfigsOrBuilderList() {
      return nodeConfigs_;
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public int getNodeConfigsCount() {
      return nodeConfigs_.size();
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeConfig getNodeConfigs(int index) {
      return nodeConfigs_.get(index);
    }
    /**
     * <code>repeated .NodeConfig node_configs = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNodeConfigsOrBuilder(
        int index) {
      return nodeConfigs_.get(index);
    }

    public static final int NODE_TO_REMOVE_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeToRemove_;
    /**
     * <code>string node_to_remove = 2;</code>
     */
    public java.lang.String getNodeToRemove() {
      java.lang.Object ref = nodeToRemove_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeToRemove_ = s;
        return s;
      }
    }
    /**
     * <code>string node_to_remove = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeToRemoveBytes() {
      java.lang.Object ref = nodeToRemove_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeToRemove_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodeConfigs_.size(); i++) {
        output.writeMessage(1, nodeConfigs_.get(i));
      }
      if (!getNodeToRemoveBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeToRemove_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodeConfigs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodeConfigs_.get(i));
      }
      if (!getNodeToRemoveBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeToRemove_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand)) {
        return super.equals(obj);
      }
      in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand other = (in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand) obj;

      boolean result = true;
      result = result && getNodeConfigsList()
          .equals(other.getNodeConfigsList());
      result = result && getNodeToRemove()
          .equals(other.getNodeToRemove());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeConfigsCount() > 0) {
        hash = (37 * hash) + NODE_CONFIGS_FIELD_NUMBER;
        hash = (53 * hash) + getNodeConfigsList().hashCode();
      }
      hash = (37 * hash) + NODE_TO_REMOVE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeToRemove().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RemoveNodeCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RemoveNodeCommand)
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.Builder.class);
      }

      // Construct using in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeConfigsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodeConfigsBuilder_ == null) {
          nodeConfigs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodeConfigsBuilder_.clear();
        }
        nodeToRemove_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_descriptor;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand getDefaultInstanceForType() {
        return in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.getDefaultInstance();
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand build() {
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand buildPartial() {
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand result = new in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (nodeConfigsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodeConfigs_ = java.util.Collections.unmodifiableList(nodeConfigs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodeConfigs_ = nodeConfigs_;
        } else {
          result.nodeConfigs_ = nodeConfigsBuilder_.build();
        }
        result.nodeToRemove_ = nodeToRemove_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand) {
          return mergeFrom((in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand other) {
        if (other == in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.getDefaultInstance()) return this;
        if (nodeConfigsBuilder_ == null) {
          if (!other.nodeConfigs_.isEmpty()) {
            if (nodeConfigs_.isEmpty()) {
              nodeConfigs_ = other.nodeConfigs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeConfigsIsMutable();
              nodeConfigs_.addAll(other.nodeConfigs_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeConfigs_.isEmpty()) {
            if (nodeConfigsBuilder_.isEmpty()) {
              nodeConfigsBuilder_.dispose();
              nodeConfigsBuilder_ = null;
              nodeConfigs_ = other.nodeConfigs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodeConfigsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeConfigsFieldBuilder() : null;
            } else {
              nodeConfigsBuilder_.addAllMessages(other.nodeConfigs_);
            }
          }
        }
        if (!other.getNodeToRemove().isEmpty()) {
          nodeToRemove_ = other.nodeToRemove_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> nodeConfigs_ =
        java.util.Collections.emptyList();
      private void ensureNodeConfigsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodeConfigs_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeConfig>(nodeConfigs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> nodeConfigsBuilder_;

      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig> getNodeConfigsList() {
        if (nodeConfigsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeConfigs_);
        } else {
          return nodeConfigsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public int getNodeConfigsCount() {
        if (nodeConfigsBuilder_ == null) {
          return nodeConfigs_.size();
        } else {
          return nodeConfigsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig getNodeConfigs(int index) {
        if (nodeConfigsBuilder_ == null) {
          return nodeConfigs_.get(index);
        } else {
          return nodeConfigsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder setNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (nodeConfigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeConfigsIsMutable();
          nodeConfigs_.set(index, value);
          onChanged();
        } else {
          nodeConfigsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder setNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder builderForValue) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeConfigsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (nodeConfigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(value);
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig value) {
        if (nodeConfigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(index, value);
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(
          in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder builderForValue) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(builderForValue.build());
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addNodeConfigs(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder builderForValue) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeConfigsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder addAllNodeConfigs(
          java.lang.Iterable<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfig> values) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeConfigs_);
          onChanged();
        } else {
          nodeConfigsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder clearNodeConfigs() {
        if (nodeConfigsBuilder_ == null) {
          nodeConfigs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodeConfigsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public Builder removeNodeConfigs(int index) {
        if (nodeConfigsBuilder_ == null) {
          ensureNodeConfigsIsMutable();
          nodeConfigs_.remove(index);
          onChanged();
        } else {
          nodeConfigsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder getNodeConfigsBuilder(
          int index) {
        return getNodeConfigsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder getNodeConfigsOrBuilder(
          int index) {
        if (nodeConfigsBuilder_ == null) {
          return nodeConfigs_.get(index);  } else {
          return nodeConfigsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
           getNodeConfigsOrBuilderList() {
        if (nodeConfigsBuilder_ != null) {
          return nodeConfigsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeConfigs_);
        }
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder addNodeConfigsBuilder() {
        return getNodeConfigsFieldBuilder().addBuilder(
            in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder addNodeConfigsBuilder(
          int index) {
        return getNodeConfigsFieldBuilder().addBuilder(
            index, in.xnnyygn.xraft.core.log.Protos.NodeConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeConfig node_configs = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder> 
           getNodeConfigsBuilderList() {
        return getNodeConfigsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder> 
          getNodeConfigsFieldBuilder() {
        if (nodeConfigsBuilder_ == null) {
          nodeConfigsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              in.xnnyygn.xraft.core.log.Protos.NodeConfig, in.xnnyygn.xraft.core.log.Protos.NodeConfig.Builder, in.xnnyygn.xraft.core.log.Protos.NodeConfigOrBuilder>(
                  nodeConfigs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodeConfigs_ = null;
        }
        return nodeConfigsBuilder_;
      }

      private java.lang.Object nodeToRemove_ = "";
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public java.lang.String getNodeToRemove() {
        java.lang.Object ref = nodeToRemove_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeToRemove_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeToRemoveBytes() {
        java.lang.Object ref = nodeToRemove_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeToRemove_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public Builder setNodeToRemove(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeToRemove_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public Builder clearNodeToRemove() {
        
        nodeToRemove_ = getDefaultInstance().getNodeToRemove();
        onChanged();
        return this;
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public Builder setNodeToRemoveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeToRemove_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RemoveNodeCommand)
    }

    // @@protoc_insertion_point(class_scope:RemoveNodeCommand)
    private static final in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand();
    }

    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RemoveNodeCommand>
        PARSER = new com.google.protobuf.AbstractParser<RemoveNodeCommand>() {
      @java.lang.Override
      public RemoveNodeCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoveNodeCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RemoveNodeCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RemoveNodeCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddNodeCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddNodeCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveNodeCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoveNodeCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023src/proto/log.proto\"4\n\nNodeConfig\022\n\n\002i" +
      "d\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"Y\n\016A" +
      "ddNodeCommand\022!\n\014node_configs\030\001 \003(\0132\013.No" +
      "deConfig\022$\n\017new_node_config\030\002 \001(\0132\013.Node" +
      "Config\"N\n\021RemoveNodeCommand\022!\n\014node_conf" +
      "igs\030\001 \003(\0132\013.NodeConfig\022\026\n\016node_to_remove" +
      "\030\002 \001(\tB#\n\031in.xnnyygn.xraft.core.logB\006Pro" +
      "tosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NodeConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NodeConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeConfig_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", });
    internal_static_AddNodeCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddNodeCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddNodeCommand_descriptor,
        new java.lang.String[] { "NodeConfigs", "NewNodeConfig", });
    internal_static_RemoveNodeCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RemoveNodeCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoveNodeCommand_descriptor,
        new java.lang.String[] { "NodeConfigs", "NodeToRemove", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
