// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/log.proto

package in.xnnyygn.xraft.core.log;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeEndpointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NodeEndpoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <code>string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 3;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code NodeEndpoint}
   */
  public  static final class NodeEndpoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NodeEndpoint)
      NodeEndpointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeEndpoint.newBuilder() to construct.
    private NodeEndpoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeEndpoint() {
      id_ = "";
      host_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeEndpoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeEndpoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeEndpoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.class, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.xnnyygn.xraft.core.log.Protos.NodeEndpoint)) {
        return super.equals(obj);
      }
      in.xnnyygn.xraft.core.log.Protos.NodeEndpoint other = (in.xnnyygn.xraft.core.log.Protos.NodeEndpoint) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NodeEndpoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NodeEndpoint)
        in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeEndpoint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeEndpoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.class, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder.class);
      }

      // Construct using in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        host_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_NodeEndpoint_descriptor;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getDefaultInstanceForType() {
        return in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance();
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint build() {
        in.xnnyygn.xraft.core.log.Protos.NodeEndpoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint buildPartial() {
        in.xnnyygn.xraft.core.log.Protos.NodeEndpoint result = new in.xnnyygn.xraft.core.log.Protos.NodeEndpoint(this);
        result.id_ = id_;
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.xnnyygn.xraft.core.log.Protos.NodeEndpoint) {
          return mergeFrom((in.xnnyygn.xraft.core.log.Protos.NodeEndpoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint other) {
        if (other == in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.xnnyygn.xraft.core.log.Protos.NodeEndpoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.xnnyygn.xraft.core.log.Protos.NodeEndpoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 2;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NodeEndpoint)
    }

    // @@protoc_insertion_point(class_scope:NodeEndpoint)
    private static final in.xnnyygn.xraft.core.log.Protos.NodeEndpoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.xnnyygn.xraft.core.log.Protos.NodeEndpoint();
    }

    public static in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeEndpoint>
        PARSER = new com.google.protobuf.AbstractParser<NodeEndpoint>() {
      @java.lang.Override
      public NodeEndpoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeEndpoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeEndpoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeEndpoint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddNodeCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddNodeCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> 
        getNodeEndpointsList();
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNodeEndpoints(int index);
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    int getNodeEndpointsCount();
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
        getNodeEndpointsOrBuilderList();
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNodeEndpointsOrBuilder(
        int index);

    /**
     * <code>.NodeEndpoint new_node_endpoint = 2;</code>
     */
    boolean hasNewNodeEndpoint();
    /**
     * <code>.NodeEndpoint new_node_endpoint = 2;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNewNodeEndpoint();
    /**
     * <code>.NodeEndpoint new_node_endpoint = 2;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNewNodeEndpointOrBuilder();
  }
  /**
   * Protobuf type {@code AddNodeCommand}
   */
  public  static final class AddNodeCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddNodeCommand)
      AddNodeCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddNodeCommand.newBuilder() to construct.
    private AddNodeCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddNodeCommand() {
      nodeEndpoints_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddNodeCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nodeEndpoints_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeEndpoints_.add(
                  input.readMessage(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.parser(), extensionRegistry));
              break;
            }
            case 18: {
              in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder subBuilder = null;
              if (newNodeEndpoint_ != null) {
                subBuilder = newNodeEndpoint_.toBuilder();
              }
              newNodeEndpoint_ = input.readMessage(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(newNodeEndpoint_);
                newNodeEndpoint_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nodeEndpoints_ = java.util.Collections.unmodifiableList(nodeEndpoints_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.Builder.class);
    }

    private int bitField0_;
    public static final int NODE_ENDPOINTS_FIELD_NUMBER = 1;
    private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> nodeEndpoints_;
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> getNodeEndpointsList() {
      return nodeEndpoints_;
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
        getNodeEndpointsOrBuilderList() {
      return nodeEndpoints_;
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public int getNodeEndpointsCount() {
      return nodeEndpoints_.size();
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNodeEndpoints(int index) {
      return nodeEndpoints_.get(index);
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNodeEndpointsOrBuilder(
        int index) {
      return nodeEndpoints_.get(index);
    }

    public static final int NEW_NODE_ENDPOINT_FIELD_NUMBER = 2;
    private in.xnnyygn.xraft.core.log.Protos.NodeEndpoint newNodeEndpoint_;
    /**
     * <code>.NodeEndpoint new_node_endpoint = 2;</code>
     */
    public boolean hasNewNodeEndpoint() {
      return newNodeEndpoint_ != null;
    }
    /**
     * <code>.NodeEndpoint new_node_endpoint = 2;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNewNodeEndpoint() {
      return newNodeEndpoint_ == null ? in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance() : newNodeEndpoint_;
    }
    /**
     * <code>.NodeEndpoint new_node_endpoint = 2;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNewNodeEndpointOrBuilder() {
      return getNewNodeEndpoint();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodeEndpoints_.size(); i++) {
        output.writeMessage(1, nodeEndpoints_.get(i));
      }
      if (newNodeEndpoint_ != null) {
        output.writeMessage(2, getNewNodeEndpoint());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodeEndpoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodeEndpoints_.get(i));
      }
      if (newNodeEndpoint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNewNodeEndpoint());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.xnnyygn.xraft.core.log.Protos.AddNodeCommand)) {
        return super.equals(obj);
      }
      in.xnnyygn.xraft.core.log.Protos.AddNodeCommand other = (in.xnnyygn.xraft.core.log.Protos.AddNodeCommand) obj;

      boolean result = true;
      result = result && getNodeEndpointsList()
          .equals(other.getNodeEndpointsList());
      result = result && (hasNewNodeEndpoint() == other.hasNewNodeEndpoint());
      if (hasNewNodeEndpoint()) {
        result = result && getNewNodeEndpoint()
            .equals(other.getNewNodeEndpoint());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeEndpointsCount() > 0) {
        hash = (37 * hash) + NODE_ENDPOINTS_FIELD_NUMBER;
        hash = (53 * hash) + getNodeEndpointsList().hashCode();
      }
      if (hasNewNodeEndpoint()) {
        hash = (37 * hash) + NEW_NODE_ENDPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getNewNodeEndpoint().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.xnnyygn.xraft.core.log.Protos.AddNodeCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddNodeCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddNodeCommand)
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.Builder.class);
      }

      // Construct using in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeEndpointsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodeEndpointsBuilder_ == null) {
          nodeEndpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodeEndpointsBuilder_.clear();
        }
        if (newNodeEndpointBuilder_ == null) {
          newNodeEndpoint_ = null;
        } else {
          newNodeEndpoint_ = null;
          newNodeEndpointBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_AddNodeCommand_descriptor;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand getDefaultInstanceForType() {
        return in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.getDefaultInstance();
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand build() {
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand buildPartial() {
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommand result = new in.xnnyygn.xraft.core.log.Protos.AddNodeCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (nodeEndpointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodeEndpoints_ = java.util.Collections.unmodifiableList(nodeEndpoints_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodeEndpoints_ = nodeEndpoints_;
        } else {
          result.nodeEndpoints_ = nodeEndpointsBuilder_.build();
        }
        if (newNodeEndpointBuilder_ == null) {
          result.newNodeEndpoint_ = newNodeEndpoint_;
        } else {
          result.newNodeEndpoint_ = newNodeEndpointBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.xnnyygn.xraft.core.log.Protos.AddNodeCommand) {
          return mergeFrom((in.xnnyygn.xraft.core.log.Protos.AddNodeCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.xnnyygn.xraft.core.log.Protos.AddNodeCommand other) {
        if (other == in.xnnyygn.xraft.core.log.Protos.AddNodeCommand.getDefaultInstance()) return this;
        if (nodeEndpointsBuilder_ == null) {
          if (!other.nodeEndpoints_.isEmpty()) {
            if (nodeEndpoints_.isEmpty()) {
              nodeEndpoints_ = other.nodeEndpoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeEndpointsIsMutable();
              nodeEndpoints_.addAll(other.nodeEndpoints_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeEndpoints_.isEmpty()) {
            if (nodeEndpointsBuilder_.isEmpty()) {
              nodeEndpointsBuilder_.dispose();
              nodeEndpointsBuilder_ = null;
              nodeEndpoints_ = other.nodeEndpoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodeEndpointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeEndpointsFieldBuilder() : null;
            } else {
              nodeEndpointsBuilder_.addAllMessages(other.nodeEndpoints_);
            }
          }
        }
        if (other.hasNewNodeEndpoint()) {
          mergeNewNodeEndpoint(other.getNewNodeEndpoint());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.xnnyygn.xraft.core.log.Protos.AddNodeCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.xnnyygn.xraft.core.log.Protos.AddNodeCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> nodeEndpoints_ =
        java.util.Collections.emptyList();
      private void ensureNodeEndpointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodeEndpoints_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint>(nodeEndpoints_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> nodeEndpointsBuilder_;

      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> getNodeEndpointsList() {
        if (nodeEndpointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeEndpoints_);
        } else {
          return nodeEndpointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public int getNodeEndpointsCount() {
        if (nodeEndpointsBuilder_ == null) {
          return nodeEndpoints_.size();
        } else {
          return nodeEndpointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNodeEndpoints(int index) {
        if (nodeEndpointsBuilder_ == null) {
          return nodeEndpoints_.get(index);
        } else {
          return nodeEndpointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder setNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (nodeEndpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.set(index, value);
          onChanged();
        } else {
          nodeEndpointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder setNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder builderForValue) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeEndpointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (nodeEndpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(value);
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (nodeEndpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(index, value);
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder builderForValue) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(builderForValue.build());
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder builderForValue) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addAllNodeEndpoints(
          java.lang.Iterable<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> values) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeEndpoints_);
          onChanged();
        } else {
          nodeEndpointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder clearNodeEndpoints() {
        if (nodeEndpointsBuilder_ == null) {
          nodeEndpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodeEndpointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder removeNodeEndpoints(int index) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.remove(index);
          onChanged();
        } else {
          nodeEndpointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder getNodeEndpointsBuilder(
          int index) {
        return getNodeEndpointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNodeEndpointsOrBuilder(
          int index) {
        if (nodeEndpointsBuilder_ == null) {
          return nodeEndpoints_.get(index);  } else {
          return nodeEndpointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
           getNodeEndpointsOrBuilderList() {
        if (nodeEndpointsBuilder_ != null) {
          return nodeEndpointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeEndpoints_);
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder addNodeEndpointsBuilder() {
        return getNodeEndpointsFieldBuilder().addBuilder(
            in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder addNodeEndpointsBuilder(
          int index) {
        return getNodeEndpointsFieldBuilder().addBuilder(
            index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder> 
           getNodeEndpointsBuilderList() {
        return getNodeEndpointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
          getNodeEndpointsFieldBuilder() {
        if (nodeEndpointsBuilder_ == null) {
          nodeEndpointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder>(
                  nodeEndpoints_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodeEndpoints_ = null;
        }
        return nodeEndpointsBuilder_;
      }

      private in.xnnyygn.xraft.core.log.Protos.NodeEndpoint newNodeEndpoint_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> newNodeEndpointBuilder_;
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public boolean hasNewNodeEndpoint() {
        return newNodeEndpointBuilder_ != null || newNodeEndpoint_ != null;
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNewNodeEndpoint() {
        if (newNodeEndpointBuilder_ == null) {
          return newNodeEndpoint_ == null ? in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance() : newNodeEndpoint_;
        } else {
          return newNodeEndpointBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public Builder setNewNodeEndpoint(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (newNodeEndpointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          newNodeEndpoint_ = value;
          onChanged();
        } else {
          newNodeEndpointBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public Builder setNewNodeEndpoint(
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder builderForValue) {
        if (newNodeEndpointBuilder_ == null) {
          newNodeEndpoint_ = builderForValue.build();
          onChanged();
        } else {
          newNodeEndpointBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public Builder mergeNewNodeEndpoint(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (newNodeEndpointBuilder_ == null) {
          if (newNodeEndpoint_ != null) {
            newNodeEndpoint_ =
              in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.newBuilder(newNodeEndpoint_).mergeFrom(value).buildPartial();
          } else {
            newNodeEndpoint_ = value;
          }
          onChanged();
        } else {
          newNodeEndpointBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public Builder clearNewNodeEndpoint() {
        if (newNodeEndpointBuilder_ == null) {
          newNodeEndpoint_ = null;
          onChanged();
        } else {
          newNodeEndpoint_ = null;
          newNodeEndpointBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder getNewNodeEndpointBuilder() {
        
        onChanged();
        return getNewNodeEndpointFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNewNodeEndpointOrBuilder() {
        if (newNodeEndpointBuilder_ != null) {
          return newNodeEndpointBuilder_.getMessageOrBuilder();
        } else {
          return newNodeEndpoint_ == null ?
              in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance() : newNodeEndpoint_;
        }
      }
      /**
       * <code>.NodeEndpoint new_node_endpoint = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
          getNewNodeEndpointFieldBuilder() {
        if (newNodeEndpointBuilder_ == null) {
          newNodeEndpointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder>(
                  getNewNodeEndpoint(),
                  getParentForChildren(),
                  isClean());
          newNodeEndpoint_ = null;
        }
        return newNodeEndpointBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddNodeCommand)
    }

    // @@protoc_insertion_point(class_scope:AddNodeCommand)
    private static final in.xnnyygn.xraft.core.log.Protos.AddNodeCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.xnnyygn.xraft.core.log.Protos.AddNodeCommand();
    }

    public static in.xnnyygn.xraft.core.log.Protos.AddNodeCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddNodeCommand>
        PARSER = new com.google.protobuf.AbstractParser<AddNodeCommand>() {
      @java.lang.Override
      public AddNodeCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddNodeCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddNodeCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddNodeCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public in.xnnyygn.xraft.core.log.Protos.AddNodeCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RemoveNodeCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RemoveNodeCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> 
        getNodeEndpointsList();
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNodeEndpoints(int index);
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    int getNodeEndpointsCount();
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
        getNodeEndpointsOrBuilderList();
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNodeEndpointsOrBuilder(
        int index);

    /**
     * <code>string node_to_remove = 2;</code>
     */
    java.lang.String getNodeToRemove();
    /**
     * <code>string node_to_remove = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeToRemoveBytes();
  }
  /**
   * Protobuf type {@code RemoveNodeCommand}
   */
  public  static final class RemoveNodeCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RemoveNodeCommand)
      RemoveNodeCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RemoveNodeCommand.newBuilder() to construct.
    private RemoveNodeCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RemoveNodeCommand() {
      nodeEndpoints_ = java.util.Collections.emptyList();
      nodeToRemove_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RemoveNodeCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nodeEndpoints_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodeEndpoints_.add(
                  input.readMessage(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeToRemove_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nodeEndpoints_ = java.util.Collections.unmodifiableList(nodeEndpoints_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.Builder.class);
    }

    private int bitField0_;
    public static final int NODE_ENDPOINTS_FIELD_NUMBER = 1;
    private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> nodeEndpoints_;
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> getNodeEndpointsList() {
      return nodeEndpoints_;
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
        getNodeEndpointsOrBuilderList() {
      return nodeEndpoints_;
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public int getNodeEndpointsCount() {
      return nodeEndpoints_.size();
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNodeEndpoints(int index) {
      return nodeEndpoints_.get(index);
    }
    /**
     * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
     */
    public in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNodeEndpointsOrBuilder(
        int index) {
      return nodeEndpoints_.get(index);
    }

    public static final int NODE_TO_REMOVE_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeToRemove_;
    /**
     * <code>string node_to_remove = 2;</code>
     */
    public java.lang.String getNodeToRemove() {
      java.lang.Object ref = nodeToRemove_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeToRemove_ = s;
        return s;
      }
    }
    /**
     * <code>string node_to_remove = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeToRemoveBytes() {
      java.lang.Object ref = nodeToRemove_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeToRemove_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodeEndpoints_.size(); i++) {
        output.writeMessage(1, nodeEndpoints_.get(i));
      }
      if (!getNodeToRemoveBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeToRemove_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodeEndpoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodeEndpoints_.get(i));
      }
      if (!getNodeToRemoveBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeToRemove_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand)) {
        return super.equals(obj);
      }
      in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand other = (in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand) obj;

      boolean result = true;
      result = result && getNodeEndpointsList()
          .equals(other.getNodeEndpointsList());
      result = result && getNodeToRemove()
          .equals(other.getNodeToRemove());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeEndpointsCount() > 0) {
        hash = (37 * hash) + NODE_ENDPOINTS_FIELD_NUMBER;
        hash = (53 * hash) + getNodeEndpointsList().hashCode();
      }
      hash = (37 * hash) + NODE_TO_REMOVE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeToRemove().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RemoveNodeCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RemoveNodeCommand)
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.class, in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.Builder.class);
      }

      // Construct using in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeEndpointsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodeEndpointsBuilder_ == null) {
          nodeEndpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodeEndpointsBuilder_.clear();
        }
        nodeToRemove_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.xnnyygn.xraft.core.log.Protos.internal_static_RemoveNodeCommand_descriptor;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand getDefaultInstanceForType() {
        return in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.getDefaultInstance();
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand build() {
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand buildPartial() {
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand result = new in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (nodeEndpointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodeEndpoints_ = java.util.Collections.unmodifiableList(nodeEndpoints_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodeEndpoints_ = nodeEndpoints_;
        } else {
          result.nodeEndpoints_ = nodeEndpointsBuilder_.build();
        }
        result.nodeToRemove_ = nodeToRemove_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand) {
          return mergeFrom((in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand other) {
        if (other == in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand.getDefaultInstance()) return this;
        if (nodeEndpointsBuilder_ == null) {
          if (!other.nodeEndpoints_.isEmpty()) {
            if (nodeEndpoints_.isEmpty()) {
              nodeEndpoints_ = other.nodeEndpoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeEndpointsIsMutable();
              nodeEndpoints_.addAll(other.nodeEndpoints_);
            }
            onChanged();
          }
        } else {
          if (!other.nodeEndpoints_.isEmpty()) {
            if (nodeEndpointsBuilder_.isEmpty()) {
              nodeEndpointsBuilder_.dispose();
              nodeEndpointsBuilder_ = null;
              nodeEndpoints_ = other.nodeEndpoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodeEndpointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeEndpointsFieldBuilder() : null;
            } else {
              nodeEndpointsBuilder_.addAllMessages(other.nodeEndpoints_);
            }
          }
        }
        if (!other.getNodeToRemove().isEmpty()) {
          nodeToRemove_ = other.nodeToRemove_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> nodeEndpoints_ =
        java.util.Collections.emptyList();
      private void ensureNodeEndpointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodeEndpoints_ = new java.util.ArrayList<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint>(nodeEndpoints_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> nodeEndpointsBuilder_;

      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> getNodeEndpointsList() {
        if (nodeEndpointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodeEndpoints_);
        } else {
          return nodeEndpointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public int getNodeEndpointsCount() {
        if (nodeEndpointsBuilder_ == null) {
          return nodeEndpoints_.size();
        } else {
          return nodeEndpointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint getNodeEndpoints(int index) {
        if (nodeEndpointsBuilder_ == null) {
          return nodeEndpoints_.get(index);
        } else {
          return nodeEndpointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder setNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (nodeEndpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.set(index, value);
          onChanged();
        } else {
          nodeEndpointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder setNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder builderForValue) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeEndpointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (nodeEndpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(value);
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint value) {
        if (nodeEndpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(index, value);
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder builderForValue) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(builderForValue.build());
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addNodeEndpoints(
          int index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder builderForValue) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeEndpointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder addAllNodeEndpoints(
          java.lang.Iterable<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpoint> values) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodeEndpoints_);
          onChanged();
        } else {
          nodeEndpointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder clearNodeEndpoints() {
        if (nodeEndpointsBuilder_ == null) {
          nodeEndpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodeEndpointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public Builder removeNodeEndpoints(int index) {
        if (nodeEndpointsBuilder_ == null) {
          ensureNodeEndpointsIsMutable();
          nodeEndpoints_.remove(index);
          onChanged();
        } else {
          nodeEndpointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder getNodeEndpointsBuilder(
          int index) {
        return getNodeEndpointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder getNodeEndpointsOrBuilder(
          int index) {
        if (nodeEndpointsBuilder_ == null) {
          return nodeEndpoints_.get(index);  } else {
          return nodeEndpointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public java.util.List<? extends in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
           getNodeEndpointsOrBuilderList() {
        if (nodeEndpointsBuilder_ != null) {
          return nodeEndpointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodeEndpoints_);
        }
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder addNodeEndpointsBuilder() {
        return getNodeEndpointsFieldBuilder().addBuilder(
            in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder addNodeEndpointsBuilder(
          int index) {
        return getNodeEndpointsFieldBuilder().addBuilder(
            index, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .NodeEndpoint node_endpoints = 1;</code>
       */
      public java.util.List<in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder> 
           getNodeEndpointsBuilderList() {
        return getNodeEndpointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder> 
          getNodeEndpointsFieldBuilder() {
        if (nodeEndpointsBuilder_ == null) {
          nodeEndpointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              in.xnnyygn.xraft.core.log.Protos.NodeEndpoint, in.xnnyygn.xraft.core.log.Protos.NodeEndpoint.Builder, in.xnnyygn.xraft.core.log.Protos.NodeEndpointOrBuilder>(
                  nodeEndpoints_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodeEndpoints_ = null;
        }
        return nodeEndpointsBuilder_;
      }

      private java.lang.Object nodeToRemove_ = "";
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public java.lang.String getNodeToRemove() {
        java.lang.Object ref = nodeToRemove_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeToRemove_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeToRemoveBytes() {
        java.lang.Object ref = nodeToRemove_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeToRemove_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public Builder setNodeToRemove(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeToRemove_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public Builder clearNodeToRemove() {
        
        nodeToRemove_ = getDefaultInstance().getNodeToRemove();
        onChanged();
        return this;
      }
      /**
       * <code>string node_to_remove = 2;</code>
       */
      public Builder setNodeToRemoveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeToRemove_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RemoveNodeCommand)
    }

    // @@protoc_insertion_point(class_scope:RemoveNodeCommand)
    private static final in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand();
    }

    public static in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RemoveNodeCommand>
        PARSER = new com.google.protobuf.AbstractParser<RemoveNodeCommand>() {
      @java.lang.Override
      public RemoveNodeCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoveNodeCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RemoveNodeCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RemoveNodeCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public in.xnnyygn.xraft.core.log.Protos.RemoveNodeCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeEndpoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeEndpoint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddNodeCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddNodeCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveNodeCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoveNodeCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023src/proto/log.proto\"6\n\014NodeEndpoint\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"a\n" +
      "\016AddNodeCommand\022%\n\016node_endpoints\030\001 \003(\0132" +
      "\r.NodeEndpoint\022(\n\021new_node_endpoint\030\002 \001(" +
      "\0132\r.NodeEndpoint\"R\n\021RemoveNodeCommand\022%\n" +
      "\016node_endpoints\030\001 \003(\0132\r.NodeEndpoint\022\026\n\016" +
      "node_to_remove\030\002 \001(\tB#\n\031in.xnnyygn.xraft" +
      ".core.logB\006Protosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NodeEndpoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NodeEndpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeEndpoint_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", });
    internal_static_AddNodeCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddNodeCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddNodeCommand_descriptor,
        new java.lang.String[] { "NodeEndpoints", "NewNodeEndpoint", });
    internal_static_RemoveNodeCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RemoveNodeCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoveNodeCommand_descriptor,
        new java.lang.String[] { "NodeEndpoints", "NodeToRemove", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
